//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev._public.intellix;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LanguageDetection.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LanguageDetection"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Auto"/&gt;
 *     &lt;enumeration value="FallbackSystemCulture"/&gt;
 *     &lt;enumeration value="FallbackExplicite"/&gt;
 *     &lt;enumeration value="Explicite"/&gt;
 *     &lt;enumeration value="DocuWareLanguageIdentifier"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "LanguageDetection")
@XmlEnum
public enum LanguageDetection {


    /**
     * The OCR could automatically detect the language.
     * 
     */
    @XmlEnumValue("Auto")
    AUTO("Auto"),

    /**
     * The OCR could not automatically detect the language and used the culture of system the OCR was run.
     * 
     */
    @XmlEnumValue("FallbackSystemCulture")
    FALLBACK_SYSTEM_CULTURE("FallbackSystemCulture"),

    /**
     * The OCR could not automatically detect the language and used the languages which are explicitely specified by a user.
     * 
     */
    @XmlEnumValue("FallbackExplicite")
    FALLBACK_EXPLICITE("FallbackExplicite"),

    /**
     * The OCR did not try to automatically detect any language. Only the languages which are explicitely specified by a user are used.
     * 
     */
    @XmlEnumValue("Explicite")
    EXPLICITE("Explicite"),

    /**
     * The language was detected by the majority voting algorithm used inside DocuWare.
     * 
     */
    @XmlEnumValue("DocuWareLanguageIdentifier")
    DOCU_WARE_LANGUAGE_IDENTIFIER("DocuWareLanguageIdentifier");
    private final String value;

    LanguageDetection(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LanguageDetection fromValue(String v) {
        for (LanguageDetection c: LanguageDetection.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
