//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev._public.intellix;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LineStyle.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LineStyle"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="none"/&gt;
 *     &lt;enumeration value="single"/&gt;
 *     &lt;enumeration value="dotted"/&gt;
 *     &lt;enumeration value="thick"/&gt;
 *     &lt;enumeration value="dash"/&gt;
 *     &lt;enumeration value="double"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "LineStyle")
@XmlEnum
public enum LineStyle {


    /**
     * The line isn't visible 
     * 
     */
    @XmlEnumValue("none")
    NONE("none"),

    /**
     * The line is a single continous line
     * 
     */
    @XmlEnumValue("single")
    SINGLE("single"),

    /**
     * The line consist of many dot
     * 
     */
    @XmlEnumValue("dotted")
    DOTTED("dotted"),

    /**
     * A thick continous line
     * 
     */
    @XmlEnumValue("thick")
    THICK("thick"),

    /**
     * The line consist of many dash
     * 
     */
    @XmlEnumValue("dash")
    DASH("dash"),

    /**
     * Two single continous line
     * 
     */
    @XmlEnumValue("double")
    DOUBLE("double");
    private final String value;

    LineStyle(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LineStyle fromValue(String v) {
        for (LineStyle c: LineStyle.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
