//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev._public.intellix;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TableZone complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TableZone"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://dev.docuware.com/public/intellix}RectangleBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="gridT" type="{http://dev.docuware.com/public/intellix}gridTable"/&gt;
 *         &lt;element name="Cz" type="{http://dev.docuware.com/public/intellix}CellZone" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TableZone", propOrder = {
    "gridT",
    "cz"
})
public class TableZone
    extends RectangleBase
{

    @XmlElement(required = true)
    protected GridTable gridT;
    @XmlElement(name = "Cz", required = true)
    protected List<CellZone> cz;

    /**
     * Gets the value of the gridT property.
     * 
     * @return
     *     possible object is
     *     {@link GridTable }
     *     
     */
    public GridTable getGridT() {
        return gridT;
    }

    /**
     * Sets the value of the gridT property.
     * 
     * @param value
     *     allowed object is
     *     {@link GridTable }
     *     
     */
    public void setGridT(GridTable value) {
        this.gridT = value;
    }

    /**
     * Gets the value of the cz property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cz property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCz().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CellZone }
     * 
     * 
     */
    public List<CellZone> getCz() {
        if (cz == null) {
            cz = new ArrayList<CellZone>();
        }
        return this.cz;
    }

}
