RestClients:
  DocuWare:
    UUID: 02d1eec1-32e9-4316-afc3-793448486203
    Url: http://{ivy.engine.host}:{ivy.engine.http.port}/{ivy.request.application}/api/docuWareMock
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    - com.axonivy.market.docuware.connector.test.DocuWareAuthTestFeature
    - org.glassfish.jersey.media.multipart.MultiPartFeature
    Properties:
      com.sun.jersey.impl.client.httpclient.handleCookies: 'true'
      http.protocol.handle-redirects: 'true'
      username: TESTUSER
      password: ${decrypt:\u0015\u007F\u0046\u00C2\u00B0\u007C\u003E\u0077\u006A\u00BD\u0052\u00DF\u009F\u00FE\u00EB\u00A4\u0089\u00B8\u005F\u00B3\u0064\u008D\u00D0\u00E0\u0052\u00A0\u00C9\u00E9\u0096\u00DE\u0072\u0099\u009A\u00BC\u00E5\u0026\u00F3\u009C\u0007\u00D9\u004C\u0052\u00B9\u00FE\u0094\u0007\u00BF\u00BF\u00EC\u00EC\u00D4\u004B\u00F5\u0011\u00B3\u0039\u0004\u00C4\u0083\u0020\u001A\u00C7\u0046\u0022\u00FF\u0012\u0013\u005B\u0083\u007B\u000C\u0089\u0065\u00F7\u0096\u000E\u0080\u0055\u0052\u009B}
      hostid: TESTHOST
      JSON.Serialization.PROPERTY_INCLUSION: NON_NULL
    OpenAPI:
      SpecUrl: file:///X:/AxonIvy/marketplace/docuware/openapi-handmade.json
      Namespace: com.axonivy.connector.docuware.connector.model
