//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.annotations;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HttpMethod.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HttpMethod"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Get"/&gt;
 *     &lt;enumeration value="Put"/&gt;
 *     &lt;enumeration value="Post"/&gt;
 *     &lt;enumeration value="Delete"/&gt;
 *     &lt;enumeration value="Head"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "HttpMethod")
@XmlEnum
public enum HttpMethod {

    @XmlEnumValue("Get")
    GET("Get"),
    @XmlEnumValue("Put")
    PUT("Put"),
    @XmlEnumValue("Post")
    POST("Post"),
    @XmlEnumValue("Delete")
    DELETE("Delete"),
    @XmlEnumValue("Head")
    HEAD("Head");
    private final String value;

    HttpMethod(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HttpMethod fromValue(String v) {
        for (HttpMethod c: HttpMethod.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
