//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnnotationTools.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AnnotationTools"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Line"/&gt;
 *     &lt;enumeration value="Arrow"/&gt;
 *     &lt;enumeration value="Rectangle"/&gt;
 *     &lt;enumeration value="Ellipse"/&gt;
 *     &lt;enumeration value="FilledEllipse"/&gt;
 *     &lt;enumeration value="FilledRectangle"/&gt;
 *     &lt;enumeration value="TransparentEllipse"/&gt;
 *     &lt;enumeration value="TransparentRectangle"/&gt;
 *     &lt;enumeration value="Marker"/&gt;
 *     &lt;enumeration value="Text"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AnnotationTools")
@XmlEnum
public enum AnnotationTools {

    @XmlEnumValue("Line")
    LINE("Line"),
    @XmlEnumValue("Arrow")
    ARROW("Arrow"),
    @XmlEnumValue("Rectangle")
    RECTANGLE("Rectangle"),
    @XmlEnumValue("Ellipse")
    ELLIPSE("Ellipse"),
    @XmlEnumValue("FilledEllipse")
    FILLED_ELLIPSE("FilledEllipse"),
    @XmlEnumValue("FilledRectangle")
    FILLED_RECTANGLE("FilledRectangle"),
    @XmlEnumValue("TransparentEllipse")
    TRANSPARENT_ELLIPSE("TransparentEllipse"),
    @XmlEnumValue("TransparentRectangle")
    TRANSPARENT_RECTANGLE("TransparentRectangle"),
    @XmlEnumValue("Marker")
    MARKER("Marker"),
    @XmlEnumValue("Text")
    TEXT("Text");
    private final String value;

    AnnotationTools(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AnnotationTools fromValue(String v) {
        for (AnnotationTools c: AnnotationTools.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
