//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A class which contains data for batch update processes.
 * 
 * <p>Java class for BatchUpdateProcess complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BatchUpdateProcess"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Source" type="{http://dev.docuware.com/schema/public/services/platform}BatchUpdateSource"/&gt;
 *         &lt;element name="Data" type="{http://dev.docuware.com/schema/public/services/platform}BatchUpdateProcessData"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BatchUpdateProcess", propOrder = {
    "source",
    "data"
})
public class BatchUpdateProcess {

    @XmlElement(name = "Source", required = true)
    protected BatchUpdateSource source;
    @XmlElement(name = "Data", required = true)
    protected BatchUpdateProcessData data;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link BatchUpdateSource }
     *     
     */
    public BatchUpdateSource getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatchUpdateSource }
     *     
     */
    public void setSource(BatchUpdateSource value) {
        this.source = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link BatchUpdateProcessData }
     *     
     */
    public BatchUpdateProcessData getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatchUpdateProcessData }
     *     
     */
    public void setData(BatchUpdateProcessData value) {
        this.data = value;
    }

}
