//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Parameters for CheckIn action
 * 
 * <p>Java class for CheckInActionParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CheckInActionParameters"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://dev.docuware.com/schema/public/services/platform}DocumentActionParameters"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DocumentVersion" type="{http://dev.docuware.com/schema/public/services/platform}DocumentVersion"/&gt;
 *         &lt;element name="CheckInReturnDocument" type="{http://dev.docuware.com/schema/public/services/platform}CheckInReturnDocument"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Comments" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CheckInActionParameters", propOrder = {
    "documentVersion",
    "checkInReturnDocument"
})
public class CheckInActionParameters
    extends DocumentActionParameters
{

    @XmlElement(name = "DocumentVersion", required = true)
    protected DocumentVersion documentVersion;
    @XmlElement(name = "CheckInReturnDocument", required = true, defaultValue = "Original")
    @XmlSchemaType(name = "string")
    protected CheckInReturnDocument checkInReturnDocument;
    @XmlAttribute(name = "Comments")
    protected String comments;

    /**
     * Gets the value of the documentVersion property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentVersion }
     *     
     */
    public DocumentVersion getDocumentVersion() {
        return documentVersion;
    }

    /**
     * Sets the value of the documentVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentVersion }
     *     
     */
    public void setDocumentVersion(DocumentVersion value) {
        this.documentVersion = value;
    }

    /**
     * Gets the value of the checkInReturnDocument property.
     * 
     * @return
     *     possible object is
     *     {@link CheckInReturnDocument }
     *     
     */
    public CheckInReturnDocument getCheckInReturnDocument() {
        return checkInReturnDocument;
    }

    /**
     * Sets the value of the checkInReturnDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckInReturnDocument }
     *     
     */
    public void setCheckInReturnDocument(CheckInReturnDocument value) {
        this.checkInReturnDocument = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

}
