//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChecksumStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ChecksumStatusType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="NotChecked"/&gt;
 *     &lt;enumeration value="Ok"/&gt;
 *     &lt;enumeration value="NoChecksum"/&gt;
 *     &lt;enumeration value="WrongChecksum"/&gt;
 *     &lt;enumeration value="FailedToCheck"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ChecksumStatusType")
@XmlEnum
public enum ChecksumStatusType {


    /**
     * 
     *             The checksums is not checked.
     *           
     * 
     */
    @XmlEnumValue("NotChecked")
    NOT_CHECKED("NotChecked"),

    /**
     * 
     *             All checksums are correct.
     *           
     * 
     */
    @XmlEnumValue("Ok")
    OK("Ok"),

    /**
     * 
     *             There are no checksums.
     *           
     * 
     */
    @XmlEnumValue("NoChecksum")
    NO_CHECKSUM("NoChecksum"),

    /**
     * 
     *             As least one of the checksum is wrong.
     *           
     * 
     */
    @XmlEnumValue("WrongChecksum")
    WRONG_CHECKSUM("WrongChecksum"),

    /**
     * 
     *             A problem has occurred while checking the checksum.
     *           
     * 
     */
    @XmlEnumValue("FailedToCheck")
    FAILED_TO_CHECK("FailedToCheck");
    private final String value;

    ChecksumStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ChecksumStatusType fromValue(String v) {
        for (ChecksumStatusType c: ChecksumStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
