//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import com.docuware.dev.schema._public.services.Links;


/**
 * Base dialog field definition
 * 
 * <p>Java class for DialogFieldBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DialogFieldBase"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Mask" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MaskErrorText" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SampleEditText" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PrefillValue" type="{http://dev.docuware.com/schema/public/services/platform}DocumentIndexFieldValue" maxOccurs="2" minOccurs="0"/&gt;
 *         &lt;element name="DynamicPrefillValue" type="{http://dev.docuware.com/schema/public/services/platform}DynamicValueType" maxOccurs="2" minOccurs="0"/&gt;
 *         &lt;element name="SelectListInfos" type="{http://dev.docuware.com/schema/public/services/platform}SelectListInfos" minOccurs="0"/&gt;
 *         &lt;element ref="{http://dev.docuware.com/schema/public/services}Links" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="DBFieldName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DlgLabel" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Locked" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="ReadOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="NotEmpty" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="Visible" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="Length" type="{http://www.w3.org/2001/XMLSchema}int" default="-1" /&gt;
 *       &lt;attribute name="Precision" type="{http://www.w3.org/2001/XMLSchema}int" default="0" /&gt;
 *       &lt;attribute name="AllowExtendedSearch" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="AllowFiltering" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="SelectListOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="SelectListType" type="{http://dev.docuware.com/schema/public/services/platform}SelectListType" default="Standard" /&gt;
 *       &lt;attribute name="AssignedInternalSelectList" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="SequenceId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SelectListsAssigned" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DialogFieldBase", propOrder = {
    "mask",
    "maskErrorText",
    "sampleEditText",
    "prefillValue",
    "dynamicPrefillValue",
    "selectListInfos",
    "links"
})
@XmlSeeAlso({
    DialogField.class
})
public class DialogFieldBase {

    @XmlElement(name = "Mask")
    protected String mask;
    @XmlElement(name = "MaskErrorText", required = true)
    protected String maskErrorText;
    @XmlElement(name = "SampleEditText", required = true)
    protected String sampleEditText;
    @XmlElement(name = "PrefillValue")
    protected List<DocumentIndexFieldValue> prefillValue;
    @XmlElement(name = "DynamicPrefillValue")
    @XmlSchemaType(name = "string")
    protected List<DynamicValueType> dynamicPrefillValue;
    @XmlElement(name = "SelectListInfos")
    protected SelectListInfos selectListInfos;
    @XmlElement(name = "Links", namespace = "http://dev.docuware.com/schema/public/services")
    protected Links links;
    @XmlAttribute(name = "DBFieldName", required = true)
    protected String dbFieldName;
    @XmlAttribute(name = "DlgLabel")
    protected String dlgLabel;
    @XmlAttribute(name = "Locked")
    protected Boolean locked;
    @XmlAttribute(name = "ReadOnly")
    protected Boolean readOnly;
    @XmlAttribute(name = "NotEmpty")
    protected Boolean notEmpty;
    @XmlAttribute(name = "Visible")
    protected Boolean visible;
    @XmlAttribute(name = "Length")
    protected Integer length;
    @XmlAttribute(name = "Precision")
    protected Integer precision;
    @XmlAttribute(name = "AllowExtendedSearch")
    protected Boolean allowExtendedSearch;
    @XmlAttribute(name = "AllowFiltering")
    protected Boolean allowFiltering;
    @XmlAttribute(name = "SelectListOnly")
    protected Boolean selectListOnly;
    @XmlAttribute(name = "SelectListType")
    protected SelectListType selectListType;
    @XmlAttribute(name = "AssignedInternalSelectList")
    protected Boolean assignedInternalSelectList;
    @XmlAttribute(name = "SequenceId")
    protected String sequenceId;
    @XmlAttribute(name = "SelectListsAssigned")
    protected Boolean selectListsAssigned;

    /**
     * Gets the value of the mask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMask() {
        return mask;
    }

    /**
     * Sets the value of the mask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMask(String value) {
        this.mask = value;
    }

    /**
     * Gets the value of the maskErrorText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaskErrorText() {
        return maskErrorText;
    }

    /**
     * Sets the value of the maskErrorText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaskErrorText(String value) {
        this.maskErrorText = value;
    }

    /**
     * Gets the value of the sampleEditText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSampleEditText() {
        return sampleEditText;
    }

    /**
     * Sets the value of the sampleEditText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSampleEditText(String value) {
        this.sampleEditText = value;
    }

    /**
     * Gets the value of the prefillValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prefillValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrefillValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentIndexFieldValue }
     * 
     * 
     */
    public List<DocumentIndexFieldValue> getPrefillValue() {
        if (prefillValue == null) {
            prefillValue = new ArrayList<DocumentIndexFieldValue>();
        }
        return this.prefillValue;
    }

    /**
     * Gets the value of the dynamicPrefillValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dynamicPrefillValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDynamicPrefillValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DynamicValueType }
     * 
     * 
     */
    public List<DynamicValueType> getDynamicPrefillValue() {
        if (dynamicPrefillValue == null) {
            dynamicPrefillValue = new ArrayList<DynamicValueType>();
        }
        return this.dynamicPrefillValue;
    }

    /**
     * Gets the value of the selectListInfos property.
     * 
     * @return
     *     possible object is
     *     {@link SelectListInfos }
     *     
     */
    public SelectListInfos getSelectListInfos() {
        return selectListInfos;
    }

    /**
     * Sets the value of the selectListInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectListInfos }
     *     
     */
    public void setSelectListInfos(SelectListInfos value) {
        this.selectListInfos = value;
    }

    /**
     * Gets the value of the links property.
     * 
     * @return
     *     possible object is
     *     {@link Links }
     *     
     */
    public Links getLinks() {
        return links;
    }

    /**
     * Sets the value of the links property.
     * 
     * @param value
     *     allowed object is
     *     {@link Links }
     *     
     */
    public void setLinks(Links value) {
        this.links = value;
    }

    /**
     * Gets the value of the dbFieldName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDBFieldName() {
        return dbFieldName;
    }

    /**
     * Sets the value of the dbFieldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDBFieldName(String value) {
        this.dbFieldName = value;
    }

    /**
     * Gets the value of the dlgLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlgLabel() {
        return dlgLabel;
    }

    /**
     * Sets the value of the dlgLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlgLabel(String value) {
        this.dlgLabel = value;
    }

    /**
     * Gets the value of the locked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isLocked() {
        if (locked == null) {
            return false;
        } else {
            return locked;
        }
    }

    /**
     * Sets the value of the locked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLocked(Boolean value) {
        this.locked = value;
    }

    /**
     * Gets the value of the readOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isReadOnly() {
        if (readOnly == null) {
            return false;
        } else {
            return readOnly;
        }
    }

    /**
     * Sets the value of the readOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReadOnly(Boolean value) {
        this.readOnly = value;
    }

    /**
     * Gets the value of the notEmpty property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isNotEmpty() {
        if (notEmpty == null) {
            return false;
        } else {
            return notEmpty;
        }
    }

    /**
     * Sets the value of the notEmpty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNotEmpty(Boolean value) {
        this.notEmpty = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isVisible() {
        if (visible == null) {
            return false;
        } else {
            return visible;
        }
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVisible(Boolean value) {
        this.visible = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getLength() {
        if (length == null) {
            return -1;
        } else {
            return length;
        }
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLength(Integer value) {
        this.length = value;
    }

    /**
     * Gets the value of the precision property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getPrecision() {
        if (precision == null) {
            return  0;
        } else {
            return precision;
        }
    }

    /**
     * Sets the value of the precision property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPrecision(Integer value) {
        this.precision = value;
    }

    /**
     * Gets the value of the allowExtendedSearch property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowExtendedSearch() {
        if (allowExtendedSearch == null) {
            return false;
        } else {
            return allowExtendedSearch;
        }
    }

    /**
     * Sets the value of the allowExtendedSearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowExtendedSearch(Boolean value) {
        this.allowExtendedSearch = value;
    }

    /**
     * Gets the value of the allowFiltering property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowFiltering() {
        if (allowFiltering == null) {
            return false;
        } else {
            return allowFiltering;
        }
    }

    /**
     * Sets the value of the allowFiltering property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowFiltering(Boolean value) {
        this.allowFiltering = value;
    }

    /**
     * Gets the value of the selectListOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSelectListOnly() {
        if (selectListOnly == null) {
            return false;
        } else {
            return selectListOnly;
        }
    }

    /**
     * Sets the value of the selectListOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSelectListOnly(Boolean value) {
        this.selectListOnly = value;
    }

    /**
     * Gets the value of the selectListType property.
     * 
     * @return
     *     possible object is
     *     {@link SelectListType }
     *     
     */
    public SelectListType getSelectListType() {
        if (selectListType == null) {
            return SelectListType.STANDARD;
        } else {
            return selectListType;
        }
    }

    /**
     * Sets the value of the selectListType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectListType }
     *     
     */
    public void setSelectListType(SelectListType value) {
        this.selectListType = value;
    }

    /**
     * Gets the value of the assignedInternalSelectList property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAssignedInternalSelectList() {
        if (assignedInternalSelectList == null) {
            return false;
        } else {
            return assignedInternalSelectList;
        }
    }

    /**
     * Sets the value of the assignedInternalSelectList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAssignedInternalSelectList(Boolean value) {
        this.assignedInternalSelectList = value;
    }

    /**
     * Gets the value of the sequenceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequenceId() {
        return sequenceId;
    }

    /**
     * Sets the value of the sequenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequenceId(String value) {
        this.sequenceId = value;
    }

    /**
     * Gets the value of the selectListsAssigned property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSelectListsAssigned() {
        if (selectListsAssigned == null) {
            return true;
        } else {
            return selectListsAssigned;
        }
    }

    /**
     * Sets the value of the selectListsAssigned property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSelectListsAssigned(Boolean value) {
        this.selectListsAssigned = value;
    }

}
