//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DialogTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DialogTypes"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Unknown"/&gt;
 *     &lt;enumeration value="Search"/&gt;
 *     &lt;enumeration value="Store"/&gt;
 *     &lt;enumeration value="ResultList"/&gt;
 *     &lt;enumeration value="ResultTree"/&gt;
 *     &lt;enumeration value="InfoDialog"/&gt;
 *     &lt;enumeration value="TaskList"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DialogTypes")
@XmlEnum
public enum DialogTypes {


    /**
     * Unknown type.
     * 
     */
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown"),

    /**
     * Search dialog.
     * 
     */
    @XmlEnumValue("Search")
    SEARCH("Search"),

    /**
     * Store dialog.
     * 
     */
    @XmlEnumValue("Store")
    STORE("Store"),

    /**
     * Result list.
     * 
     */
    @XmlEnumValue("ResultList")
    RESULT_LIST("ResultList"),

    /**
     * Tree view.
     * 
     */
    @XmlEnumValue("ResultTree")
    RESULT_TREE("ResultTree"),

    /**
     * Info dialog.
     * 
     */
    @XmlEnumValue("InfoDialog")
    INFO_DIALOG("InfoDialog"),

    /**
     * Task list(result list with predefiened conditions).
     * 
     */
    @XmlEnumValue("TaskList")
    TASK_LIST("TaskList");
    private final String value;

    DialogTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DialogTypes fromValue(String v) {
        for (DialogTypes c: DialogTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
