//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Dialog properties specific for Task lists
 * 
 * <p>Java class for DialogPropertiesTaskList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DialogPropertiesTaskList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://dev.docuware.com/schema/public/services/platform}DialogPropertiesResultList"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Conditions" type="{http://dev.docuware.com/schema/public/services/platform}DialogExpression"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ConditionString" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Private" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="AutoRefresh" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="AutoRefreshPeriod" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DialogPropertiesTaskList", propOrder = {
    "conditions"
})
public class DialogPropertiesTaskList
    extends DialogPropertiesResultList
{

    @XmlElement(name = "Conditions", required = true)
    protected DialogExpression conditions;
    @XmlAttribute(name = "ConditionString")
    protected String conditionString;
    @XmlAttribute(name = "Private")
    protected Boolean _private;
    @XmlAttribute(name = "AutoRefresh")
    protected Boolean autoRefresh;
    @XmlAttribute(name = "AutoRefreshPeriod")
    protected Integer autoRefreshPeriod;

    /**
     * Gets the value of the conditions property.
     * 
     * @return
     *     possible object is
     *     {@link DialogExpression }
     *     
     */
    public DialogExpression getConditions() {
        return conditions;
    }

    /**
     * Sets the value of the conditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DialogExpression }
     *     
     */
    public void setConditions(DialogExpression value) {
        this.conditions = value;
    }

    /**
     * Gets the value of the conditionString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConditionString() {
        return conditionString;
    }

    /**
     * Sets the value of the conditionString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConditionString(String value) {
        this.conditionString = value;
    }

    /**
     * Gets the value of the private property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPrivate() {
        if (_private == null) {
            return false;
        } else {
            return _private;
        }
    }

    /**
     * Sets the value of the private property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrivate(Boolean value) {
        this._private = value;
    }

    /**
     * Gets the value of the autoRefresh property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAutoRefresh() {
        if (autoRefresh == null) {
            return true;
        } else {
            return autoRefresh;
        }
    }

    /**
     * Sets the value of the autoRefresh property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoRefresh(Boolean value) {
        this.autoRefresh = value;
    }

    /**
     * Gets the value of the autoRefreshPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAutoRefreshPeriod() {
        return autoRefreshPeriod;
    }

    /**
     * Sets the value of the autoRefreshPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAutoRefreshPeriod(Integer value) {
        this.autoRefreshPeriod = value;
    }

}
