//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines a list of audit event properties.
 * 
 * <p>Java class for DocumentAuditEventInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocumentAuditEventInformation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DocumentAuditEventProperties" type="{http://dev.docuware.com/schema/public/services/platform}DocumentAuditEventProperty" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="DocumentAuditEventTableProperties" type="{http://dev.docuware.com/schema/public/services/platform}DocumentAuditEventTableProperty" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentAuditEventInformation", propOrder = {
    "documentAuditEventProperties",
    "documentAuditEventTableProperties"
})
public class DocumentAuditEventInformation {

    @XmlElement(name = "DocumentAuditEventProperties")
    protected List<DocumentAuditEventProperty> documentAuditEventProperties;
    @XmlElement(name = "DocumentAuditEventTableProperties")
    protected List<DocumentAuditEventTableProperty> documentAuditEventTableProperties;

    /**
     * Gets the value of the documentAuditEventProperties property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentAuditEventProperties property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentAuditEventProperties().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentAuditEventProperty }
     * 
     * 
     */
    public List<DocumentAuditEventProperty> getDocumentAuditEventProperties() {
        if (documentAuditEventProperties == null) {
            documentAuditEventProperties = new ArrayList<DocumentAuditEventProperty>();
        }
        return this.documentAuditEventProperties;
    }

    /**
     * Gets the value of the documentAuditEventTableProperties property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentAuditEventTableProperties property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentAuditEventTableProperties().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentAuditEventTableProperty }
     * 
     * 
     */
    public List<DocumentAuditEventTableProperty> getDocumentAuditEventTableProperties() {
        if (documentAuditEventTableProperties == null) {
            documentAuditEventTableProperties = new ArrayList<DocumentAuditEventTableProperty>();
        }
        return this.documentAuditEventTableProperties;
    }

}
