//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Base file cabinet field definition
 * 
 * <p>Java class for FileCabinetFieldBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FileCabinetFieldBase"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FixedEntry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FieldInfoText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Scope" type="{http://dev.docuware.com/schema/public/services/platform}FileCabinetFieldScope" default="User" /&gt;
 *       &lt;attribute name="Length" type="{http://www.w3.org/2001/XMLSchema}int" default="0" /&gt;
 *       &lt;attribute name="DBFieldName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DisplayName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DropLeadingZero" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="DropLeadingBlanks" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="NotEmpty" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="Precision" type="{http://www.w3.org/2001/XMLSchema}int" default="0" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FileCabinetFieldBase", propOrder = {
    "fixedEntry",
    "fieldInfoText"
})
@XmlSeeAlso({
    FileCabinetField.class
})
public class FileCabinetFieldBase {

    @XmlElement(name = "FixedEntry")
    protected String fixedEntry;
    @XmlElement(name = "FieldInfoText")
    protected String fieldInfoText;
    @XmlAttribute(name = "Scope")
    protected FileCabinetFieldScope scope;
    @XmlAttribute(name = "Length")
    protected Integer length;
    @XmlAttribute(name = "DBFieldName")
    protected String dbFieldName;
    @XmlAttribute(name = "DisplayName")
    protected String displayName;
    @XmlAttribute(name = "DropLeadingZero")
    protected Boolean dropLeadingZero;
    @XmlAttribute(name = "DropLeadingBlanks")
    protected Boolean dropLeadingBlanks;
    @XmlAttribute(name = "NotEmpty")
    protected Boolean notEmpty;
    @XmlAttribute(name = "Precision")
    protected Integer precision;

    /**
     * Gets the value of the fixedEntry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFixedEntry() {
        return fixedEntry;
    }

    /**
     * Sets the value of the fixedEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixedEntry(String value) {
        this.fixedEntry = value;
    }

    /**
     * Gets the value of the fieldInfoText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldInfoText() {
        return fieldInfoText;
    }

    /**
     * Sets the value of the fieldInfoText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldInfoText(String value) {
        this.fieldInfoText = value;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link FileCabinetFieldScope }
     *     
     */
    public FileCabinetFieldScope getScope() {
        if (scope == null) {
            return FileCabinetFieldScope.USER;
        } else {
            return scope;
        }
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileCabinetFieldScope }
     *     
     */
    public void setScope(FileCabinetFieldScope value) {
        this.scope = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getLength() {
        if (length == null) {
            return  0;
        } else {
            return length;
        }
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLength(Integer value) {
        this.length = value;
    }

    /**
     * Gets the value of the dbFieldName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDBFieldName() {
        return dbFieldName;
    }

    /**
     * Sets the value of the dbFieldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDBFieldName(String value) {
        this.dbFieldName = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the dropLeadingZero property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDropLeadingZero() {
        if (dropLeadingZero == null) {
            return false;
        } else {
            return dropLeadingZero;
        }
    }

    /**
     * Sets the value of the dropLeadingZero property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDropLeadingZero(Boolean value) {
        this.dropLeadingZero = value;
    }

    /**
     * Gets the value of the dropLeadingBlanks property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDropLeadingBlanks() {
        if (dropLeadingBlanks == null) {
            return false;
        } else {
            return dropLeadingBlanks;
        }
    }

    /**
     * Sets the value of the dropLeadingBlanks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDropLeadingBlanks(Boolean value) {
        this.dropLeadingBlanks = value;
    }

    /**
     * Gets the value of the notEmpty property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isNotEmpty() {
        if (notEmpty == null) {
            return false;
        } else {
            return notEmpty;
        }
    }

    /**
     * Sets the value of the notEmpty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNotEmpty(Boolean value) {
        this.notEmpty = value;
    }

    /**
     * Gets the value of the precision property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getPrecision() {
        if (precision == null) {
            return  0;
        } else {
            return precision;
        }
    }

    /**
     * Sets the value of the precision property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPrecision(Integer value) {
        this.precision = value;
    }

}
