//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FileDownloadType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FileDownloadType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Auto"/&gt;
 *     &lt;enumeration value="Zip"/&gt;
 *     &lt;enumeration value="PDF"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "FileDownloadType")
@XmlEnum
public enum FileDownloadType {


    /**
     * 
     *             The type of the downloaded file determined by the server automatically.
     *             In case of a single file this is directly downloaded, otherwise a ZIP file is created.
     *           
     * 
     */
    @XmlEnumValue("Auto")
    AUTO("Auto"),

    /**
     * 
     *             The files are always downloaded as ZIP file.
     *           
     * 
     */
    @XmlEnumValue("Zip")
    ZIP("Zip"),

    /**
     * 
     *             The files are always downloaded as PDF file. If more than one document is downloaded then every document is converted to PDF and the PDF files are packed in a ZIP file.
     *           
     * 
     */
    PDF("PDF");
    private final String value;

    FileDownloadType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FileDownloadType fromValue(String v) {
        for (FileDownloadType c: FileDownloadType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
