//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FileCabinetField complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FileCabinetField"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://dev.docuware.com/schema/public/services/platform}FileCabinetFieldBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TableFieldColumns" type="{http://dev.docuware.com/schema/public/services/platform}TableFieldColumns"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="UsedAsDocumentName" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FileCabinetField", propOrder = {
    "tableFieldColumns"
})
public class FileCabinetField
    extends FileCabinetFieldBase
{

    @XmlElement(name = "TableFieldColumns", required = true)
    protected TableFieldColumns tableFieldColumns;
    @XmlAttribute(name = "UsedAsDocumentName")
    protected Boolean usedAsDocumentName;

    /**
     * Gets the value of the tableFieldColumns property.
     * 
     * @return
     *     possible object is
     *     {@link TableFieldColumns }
     *     
     */
    public TableFieldColumns getTableFieldColumns() {
        return tableFieldColumns;
    }

    /**
     * Sets the value of the tableFieldColumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableFieldColumns }
     *     
     */
    public void setTableFieldColumns(TableFieldColumns value) {
        this.tableFieldColumns = value;
    }

    /**
     * Gets the value of the usedAsDocumentName property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUsedAsDocumentName() {
        if (usedAsDocumentName == null) {
            return false;
        } else {
            return usedAsDocumentName;
        }
    }

    /**
     * Sets the value of the usedAsDocumentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsedAsDocumentName(Boolean value) {
        this.usedAsDocumentName = value;
    }

}
