//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.docuware.dev.settings.common.DWRectangle;


/**
 * Define a metadata for a page
 * 
 * <p>Java class for PageData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PageData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LowQualitySize" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="TileSize" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="RenderedImageFormat" type="{http://dev.docuware.com/schema/public/services/platform}PlatformImageFormat"/&gt;
 *         &lt;element name="ContentArea" type="{http://dev.docuware.com/settings/common}DWRectangle" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="DpiX" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="DpiY" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="Width" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="Height" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PageData", propOrder = {
    "lowQualitySize",
    "tileSize",
    "renderedImageFormat",
    "contentArea"
})
public class PageData {

    @XmlElement(name = "LowQualitySize")
    protected int lowQualitySize;
    @XmlElement(name = "TileSize")
    protected int tileSize;
    @XmlElement(name = "RenderedImageFormat", required = true)
    @XmlSchemaType(name = "string")
    protected PlatformImageFormat renderedImageFormat;
    @XmlElementRef(name = "ContentArea", namespace = "http://dev.docuware.com/schema/public/services/platform", type = JAXBElement.class, required = false)
    protected JAXBElement<DWRectangle> contentArea;
    @XmlAttribute(name = "DpiX", required = true)
    protected int dpiX;
    @XmlAttribute(name = "DpiY", required = true)
    protected int dpiY;
    @XmlAttribute(name = "Width", required = true)
    protected int width;
    @XmlAttribute(name = "Height", required = true)
    protected int height;

    /**
     * Gets the value of the lowQualitySize property.
     * 
     */
    public int getLowQualitySize() {
        return lowQualitySize;
    }

    /**
     * Sets the value of the lowQualitySize property.
     * 
     */
    public void setLowQualitySize(int value) {
        this.lowQualitySize = value;
    }

    /**
     * Gets the value of the tileSize property.
     * 
     */
    public int getTileSize() {
        return tileSize;
    }

    /**
     * Sets the value of the tileSize property.
     * 
     */
    public void setTileSize(int value) {
        this.tileSize = value;
    }

    /**
     * Gets the value of the renderedImageFormat property.
     * 
     * @return
     *     possible object is
     *     {@link PlatformImageFormat }
     *     
     */
    public PlatformImageFormat getRenderedImageFormat() {
        return renderedImageFormat;
    }

    /**
     * Sets the value of the renderedImageFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlatformImageFormat }
     *     
     */
    public void setRenderedImageFormat(PlatformImageFormat value) {
        this.renderedImageFormat = value;
    }

    /**
     * Gets the value of the contentArea property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DWRectangle }{@code >}
     *     
     */
    public JAXBElement<DWRectangle> getContentArea() {
        return contentArea;
    }

    /**
     * Sets the value of the contentArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DWRectangle }{@code >}
     *     
     */
    public void setContentArea(JAXBElement<DWRectangle> value) {
        this.contentArea = value;
    }

    /**
     * Gets the value of the dpiX property.
     * 
     */
    public int getDpiX() {
        return dpiX;
    }

    /**
     * Sets the value of the dpiX property.
     * 
     */
    public void setDpiX(int value) {
        this.dpiX = value;
    }

    /**
     * Gets the value of the dpiY property.
     * 
     */
    public int getDpiY() {
        return dpiY;
    }

    /**
     * Sets the value of the dpiY property.
     * 
     */
    public void setDpiY(int value) {
        this.dpiY = value;
    }

    /**
     * Gets the value of the width property.
     * 
     */
    public int getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     */
    public void setWidth(int value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     */
    public int getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     */
    public void setHeight(int value) {
        this.height = value;
    }

}
