//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Function of result list
 * 
 * <p>Java class for ResultDialogFunction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResultDialogFunction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Type" use="required" type="{http://dev.docuware.com/schema/public/services/platform}ResultDialogFunctionType" /&gt;
 *       &lt;attribute name="InToolBar" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="AsButton" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResultDialogFunction")
public class ResultDialogFunction {

    @XmlAttribute(name = "Type", required = true)
    protected ResultDialogFunctionType type;
    @XmlAttribute(name = "InToolBar")
    protected Boolean inToolBar;
    @XmlAttribute(name = "AsButton")
    protected Boolean asButton;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ResultDialogFunctionType }
     *     
     */
    public ResultDialogFunctionType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultDialogFunctionType }
     *     
     */
    public void setType(ResultDialogFunctionType value) {
        this.type = value;
    }

    /**
     * Gets the value of the inToolBar property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isInToolBar() {
        if (inToolBar == null) {
            return false;
        } else {
            return inToolBar;
        }
    }

    /**
     * Sets the value of the inToolBar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInToolBar(Boolean value) {
        this.inToolBar = value;
    }

    /**
     * Gets the value of the asButton property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAsButton() {
        if (asButton == null) {
            return false;
        } else {
            return asButton;
        }
    }

    /**
     * Sets the value of the asButton property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAsButton(Boolean value) {
        this.asButton = value;
    }

}
