//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Stamp base type. Inherited by 3 types: TextStamp, BitmapStamp, PolyLineStamp
 * 
 * <p>Java class for StampBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StampBase"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://dev.docuware.com/schema/public/services/platform}EntryBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Location" type="{http://dev.docuware.com/schema/public/services/platform}AnnotationRectangle"/&gt;
 *         &lt;element name="HeadFont" type="{http://dev.docuware.com/schema/public/services/platform}Font"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Signature" type="{http://dev.docuware.com/schema/public/services/platform}StampSignatureType" default="No" /&gt;
 *       &lt;attribute name="UserName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Visible" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="Frame" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="ShowUser" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="ShowDate" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="ShowTime" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="SigScopeInfo" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StampBase", propOrder = {
    "location",
    "headFont"
})
@XmlSeeAlso({
    TextStampEntry.class,
    BitmapStampEntry.class,
    PolyLineStampEntry.class
})
public class StampBase
    extends EntryBase
{

    @XmlElement(name = "Location", required = true)
    protected AnnotationRectangle location;
    @XmlElement(name = "HeadFont", required = true)
    protected Font headFont;
    @XmlAttribute(name = "Signature")
    protected StampSignatureType signature;
    @XmlAttribute(name = "UserName")
    protected String userName;
    @XmlAttribute(name = "Visible")
    protected Boolean visible;
    @XmlAttribute(name = "Frame")
    protected Boolean frame;
    @XmlAttribute(name = "ShowUser")
    protected Boolean showUser;
    @XmlAttribute(name = "ShowDate")
    protected Boolean showDate;
    @XmlAttribute(name = "ShowTime")
    protected Boolean showTime;
    @XmlAttribute(name = "SigScopeInfo")
    protected String sigScopeInfo;

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotationRectangle }
     *     
     */
    public AnnotationRectangle getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotationRectangle }
     *     
     */
    public void setLocation(AnnotationRectangle value) {
        this.location = value;
    }

    /**
     * Gets the value of the headFont property.
     * 
     * @return
     *     possible object is
     *     {@link Font }
     *     
     */
    public Font getHeadFont() {
        return headFont;
    }

    /**
     * Sets the value of the headFont property.
     * 
     * @param value
     *     allowed object is
     *     {@link Font }
     *     
     */
    public void setHeadFont(Font value) {
        this.headFont = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link StampSignatureType }
     *     
     */
    public StampSignatureType getSignature() {
        if (signature == null) {
            return StampSignatureType.NO;
        } else {
            return signature;
        }
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link StampSignatureType }
     *     
     */
    public void setSignature(StampSignatureType value) {
        this.signature = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isVisible() {
        if (visible == null) {
            return true;
        } else {
            return visible;
        }
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVisible(Boolean value) {
        this.visible = value;
    }

    /**
     * Gets the value of the frame property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isFrame() {
        if (frame == null) {
            return true;
        } else {
            return frame;
        }
    }

    /**
     * Sets the value of the frame property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFrame(Boolean value) {
        this.frame = value;
    }

    /**
     * Gets the value of the showUser property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isShowUser() {
        if (showUser == null) {
            return true;
        } else {
            return showUser;
        }
    }

    /**
     * Sets the value of the showUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowUser(Boolean value) {
        this.showUser = value;
    }

    /**
     * Gets the value of the showDate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isShowDate() {
        if (showDate == null) {
            return true;
        } else {
            return showDate;
        }
    }

    /**
     * Sets the value of the showDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowDate(Boolean value) {
        this.showDate = value;
    }

    /**
     * Gets the value of the showTime property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isShowTime() {
        if (showTime == null) {
            return true;
        } else {
            return showTime;
        }
    }

    /**
     * Sets the value of the showTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowTime(Boolean value) {
        this.showTime = value;
    }

    /**
     * Gets the value of the sigScopeInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSigScopeInfo() {
        return sigScopeInfo;
    }

    /**
     * Sets the value of the sigScopeInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSigScopeInfo(String value) {
        this.sigScopeInfo = value;
    }

}
