//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SuggestionTable complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SuggestionTable"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Cell" type="{http://dev.docuware.com/schema/public/services/platform}SuggestionCellValue" maxOccurs="unbounded"/&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="HighlightRectangle" type="{http://dev.docuware.com/schema/public/services/platform}PointAndShootInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Trust" type="{http://www.w3.org/2001/XMLSchema}double" default="1" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SuggestionTable", propOrder = {
    "cell",
    "highlightRectangle"
})
public class SuggestionTable {

    @XmlElement(name = "Cell", required = true)
    protected List<SuggestionCellValue> cell;
    @XmlElement(name = "HighlightRectangle")
    protected List<PointAndShootInfo> highlightRectangle;
    @XmlAttribute(name = "Trust")
    protected Double trust;

    /**
     * Gets the value of the cell property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cell property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCell().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SuggestionCellValue }
     * 
     * 
     */
    public List<SuggestionCellValue> getCell() {
        if (cell == null) {
            cell = new ArrayList<SuggestionCellValue>();
        }
        return this.cell;
    }

    /**
     * Gets the value of the highlightRectangle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the highlightRectangle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHighlightRectangle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PointAndShootInfo }
     * 
     * 
     */
    public List<PointAndShootInfo> getHighlightRectangle() {
        if (highlightRectangle == null) {
            highlightRectangle = new ArrayList<PointAndShootInfo>();
        }
        return this.highlightRectangle;
    }

    /**
     * Gets the value of the trust property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getTrust() {
        if (trust == null) {
            return  1.0D;
        } else {
            return trust;
        }
    }

    /**
     * Sets the value of the trust property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTrust(Double value) {
        this.trust = value;
    }

}
