//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TextAnnotationToolSettings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TextAnnotationToolSettings"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://dev.docuware.com/schema/public/services/platform}AnnotationToolSettings"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FontSettings" type="{http://dev.docuware.com/schema/public/services/platform}FontSettings"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TextAnnotationToolSettings", propOrder = {
    "fontSettings"
})
public class TextAnnotationToolSettings
    extends AnnotationToolSettings
{

    @XmlElement(name = "FontSettings", required = true)
    protected FontSettings fontSettings;

    /**
     * Gets the value of the fontSettings property.
     * 
     * @return
     *     possible object is
     *     {@link FontSettings }
     *     
     */
    public FontSettings getFontSettings() {
        return fontSettings;
    }

    /**
     * Sets the value of the fontSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link FontSettings }
     *     
     */
    public void setFontSettings(FontSettings value) {
        this.fontSettings = value;
    }

}
