//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Structure for updating index fields, including the index fields values and the dialog used for updating.
 * 
 * <p>Java class for UpdateIndexFieldsInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UpdateIndexFieldsInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://dev.docuware.com/schema/public/services/platform}DocumentIndexFields"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="DialogId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NormalizeCoordinates" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateIndexFieldsInfo")
public class UpdateIndexFieldsInfo
    extends DocumentIndexFields
{

    @XmlAttribute(name = "DialogId")
    protected String dialogId;
    @XmlAttribute(name = "NormalizeCoordinates")
    protected Boolean normalizeCoordinates;

    /**
     * Gets the value of the dialogId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDialogId() {
        return dialogId;
    }

    /**
     * Sets the value of the dialogId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDialogId(String value) {
        this.dialogId = value;
    }

    /**
     * Gets the value of the normalizeCoordinates property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isNormalizeCoordinates() {
        if (normalizeCoordinates == null) {
            return false;
        } else {
            return normalizeCoordinates;
        }
    }

    /**
     * Sets the value of the normalizeCoordinates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNormalizeCoordinates(Boolean value) {
        this.normalizeCoordinates = value;
    }

}
