//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ViewerDialog complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ViewerDialog"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Mode" type="{http://dev.docuware.com/schema/public/services/platform}ViewerDialogModes" default="AdHocEditMode" /&gt;
 *       &lt;attribute name="MarkFulltextSearchHits" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ViewerDialog")
public class ViewerDialog {

    @XmlAttribute(name = "Mode")
    protected ViewerDialogModes mode;
    @XmlAttribute(name = "MarkFulltextSearchHits")
    protected Boolean markFulltextSearchHits;

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link ViewerDialogModes }
     *     
     */
    public ViewerDialogModes getMode() {
        if (mode == null) {
            return ViewerDialogModes.AD_HOC_EDIT_MODE;
        } else {
            return mode;
        }
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewerDialogModes }
     *     
     */
    public void setMode(ViewerDialogModes value) {
        this.mode = value;
    }

    /**
     * Gets the value of the markFulltextSearchHits property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isMarkFulltextSearchHits() {
        if (markFulltextSearchHits == null) {
            return true;
        } else {
            return markFulltextSearchHits;
        }
    }

    /**
     * Sets the value of the markFulltextSearchHits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMarkFulltextSearchHits(Boolean value) {
        this.markFulltextSearchHits = value;
    }

}
