//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WorkAreaType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="WorkAreaType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="None"/&gt;
 *     &lt;enumeration value="Basket"/&gt;
 *     &lt;enumeration value="Search"/&gt;
 *     &lt;enumeration value="TaskList"/&gt;
 *     &lt;enumeration value="Workflow"/&gt;
 *     &lt;enumeration value="TreeView"/&gt;
 *     &lt;enumeration value="Forms"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "WorkAreaType")
@XmlEnum
public enum WorkAreaType {

    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("Basket")
    BASKET("Basket"),
    @XmlEnumValue("Search")
    SEARCH("Search"),
    @XmlEnumValue("TaskList")
    TASK_LIST("TaskList"),
    @XmlEnumValue("Workflow")
    WORKFLOW("Workflow"),
    @XmlEnumValue("TreeView")
    TREE_VIEW("TreeView"),
    @XmlEnumValue("Forms")
    FORMS("Forms");
    private final String value;

    WorkAreaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static WorkAreaType fromValue(String v) {
        for (WorkAreaType c: WorkAreaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
