//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform.workflow;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CommonFormField complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommonFormField"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://dev.docuware.com/schema/public/services/platform/workflow}BaseForm"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PrefillValue" type="{http://dev.docuware.com/schema/public/services/platform/workflow}WFFormFieldValue"/&gt;
 *         &lt;element name="SelectListFilters" type="{http://dev.docuware.com/schema/public/services/platform/workflow}SelectListFilter" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Mandatory" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="Description" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="HasSelectList" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="IsReadOnly" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="IsSelectListOnly" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="SelectListGuid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SelectListColumn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="IsHiddenInStamp" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommonFormField", propOrder = {
    "prefillValue",
    "selectListFilters"
})
@XmlSeeAlso({
    MultiValueField.class,
    TaskDateTimeField.class,
    TaskTextField.class,
    TaskNumberField.class
})
public class CommonFormField
    extends BaseForm
{

    @XmlElement(name = "PrefillValue", required = true)
    protected WFFormFieldValue prefillValue;
    @XmlElement(name = "SelectListFilters")
    protected List<SelectListFilter> selectListFilters;
    @XmlAttribute(name = "Mandatory", required = true)
    protected boolean mandatory;
    @XmlAttribute(name = "Description", required = true)
    protected String description;
    @XmlAttribute(name = "HasSelectList", required = true)
    protected boolean hasSelectList;
    @XmlAttribute(name = "IsReadOnly", required = true)
    protected boolean isReadOnly;
    @XmlAttribute(name = "IsSelectListOnly", required = true)
    protected boolean isSelectListOnly;
    @XmlAttribute(name = "SelectListGuid", required = true)
    protected String selectListGuid;
    @XmlAttribute(name = "SelectListColumn", required = true)
    protected String selectListColumn;
    @XmlAttribute(name = "IsHiddenInStamp", required = true)
    protected boolean isHiddenInStamp;

    /**
     * Gets the value of the prefillValue property.
     * 
     * @return
     *     possible object is
     *     {@link WFFormFieldValue }
     *     
     */
    public WFFormFieldValue getPrefillValue() {
        return prefillValue;
    }

    /**
     * Sets the value of the prefillValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link WFFormFieldValue }
     *     
     */
    public void setPrefillValue(WFFormFieldValue value) {
        this.prefillValue = value;
    }

    /**
     * Gets the value of the selectListFilters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selectListFilters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelectListFilters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelectListFilter }
     * 
     * 
     */
    public List<SelectListFilter> getSelectListFilters() {
        if (selectListFilters == null) {
            selectListFilters = new ArrayList<SelectListFilter>();
        }
        return this.selectListFilters;
    }

    /**
     * Gets the value of the mandatory property.
     * 
     */
    public boolean isMandatory() {
        return mandatory;
    }

    /**
     * Sets the value of the mandatory property.
     * 
     */
    public void setMandatory(boolean value) {
        this.mandatory = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the hasSelectList property.
     * 
     */
    public boolean isHasSelectList() {
        return hasSelectList;
    }

    /**
     * Sets the value of the hasSelectList property.
     * 
     */
    public void setHasSelectList(boolean value) {
        this.hasSelectList = value;
    }

    /**
     * Gets the value of the isReadOnly property.
     * 
     */
    public boolean isIsReadOnly() {
        return isReadOnly;
    }

    /**
     * Sets the value of the isReadOnly property.
     * 
     */
    public void setIsReadOnly(boolean value) {
        this.isReadOnly = value;
    }

    /**
     * Gets the value of the isSelectListOnly property.
     * 
     */
    public boolean isIsSelectListOnly() {
        return isSelectListOnly;
    }

    /**
     * Sets the value of the isSelectListOnly property.
     * 
     */
    public void setIsSelectListOnly(boolean value) {
        this.isSelectListOnly = value;
    }

    /**
     * Gets the value of the selectListGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelectListGuid() {
        return selectListGuid;
    }

    /**
     * Sets the value of the selectListGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectListGuid(String value) {
        this.selectListGuid = value;
    }

    /**
     * Gets the value of the selectListColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelectListColumn() {
        return selectListColumn;
    }

    /**
     * Sets the value of the selectListColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectListColumn(String value) {
        this.selectListColumn = value;
    }

    /**
     * Gets the value of the isHiddenInStamp property.
     * 
     */
    public boolean isIsHiddenInStamp() {
        return isHiddenInStamp;
    }

    /**
     * Sets the value of the isHiddenInStamp property.
     * 
     */
    public void setIsHiddenInStamp(boolean value) {
        this.isHiddenInStamp = value;
    }

}
