//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform.workflow;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FormTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FormTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Link"/&gt;
 *     &lt;enumeration value="Description"/&gt;
 *     &lt;enumeration value="Password"/&gt;
 *     &lt;enumeration value="Text"/&gt;
 *     &lt;enumeration value="Decimal"/&gt;
 *     &lt;enumeration value="Date"/&gt;
 *     &lt;enumeration value="DateTime"/&gt;
 *     &lt;enumeration value="User"/&gt;
 *     &lt;enumeration value="Role"/&gt;
 *     &lt;enumeration value="SubstitutionRule"/&gt;
 *     &lt;enumeration value="Keyword"/&gt;
 *     &lt;enumeration value="Table"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "FormTypeEnum")
@XmlEnum
public enum FormTypeEnum {


    /**
     * Link form
     * 
     */
    @XmlEnumValue("Link")
    LINK("Link"),

    /**
     * Description form
     * 
     */
    @XmlEnumValue("Description")
    DESCRIPTION("Description"),

    /**
     * Password field
     * 
     */
    @XmlEnumValue("Password")
    PASSWORD("Password"),

    /**
     * Text field
     * 
     */
    @XmlEnumValue("Text")
    TEXT("Text"),

    /**
     * Decimal field
     * 
     */
    @XmlEnumValue("Decimal")
    DECIMAL("Decimal"),

    /**
     * Date field
     * 
     */
    @XmlEnumValue("Date")
    DATE("Date"),

    /**
     * DateTime field
     * 
     */
    @XmlEnumValue("DateTime")
    DATE_TIME("DateTime"),

    /**
     * User field
     * 
     */
    @XmlEnumValue("User")
    USER("User"),

    /**
     * Role field
     * 
     */
    @XmlEnumValue("Role")
    ROLE("Role"),

    /**
     * Substitution rule field
     * 
     */
    @XmlEnumValue("SubstitutionRule")
    SUBSTITUTION_RULE("SubstitutionRule"),

    /**
     * Keyword field
     * 
     */
    @XmlEnumValue("Keyword")
    KEYWORD("Keyword"),

    /**
     * Table field
     * 
     */
    @XmlEnumValue("Table")
    TABLE("Table");
    private final String value;

    FormTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FormTypeEnum fromValue(String v) {
        for (FormTypeEnum c: FormTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
