//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform.workflow;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HistoryField complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HistoryField"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Value" type="{http://dev.docuware.com/schema/public/services/platform/workflow}WFFormFieldValue"/&gt;
 *         &lt;element name="Options" type="{http://dev.docuware.com/schema/public/services/platform/workflow}HistoryFieldOptions" minOccurs="0"/&gt;
 *         &lt;element name="AssignmentType" type="{http://dev.docuware.com/schema/public/services/platform/workflow}AssignmentType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Label" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Type" use="required" type="{http://dev.docuware.com/schema/public/services/platform/workflow}HistoryFormTypeEnum" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HistoryField", propOrder = {
    "value",
    "options",
    "assignmentType"
})
@XmlSeeAlso({
    FileCabinetHistoryField.class
})
public class HistoryField {

    @XmlElement(name = "Value", required = true)
    protected WFFormFieldValue value;
    @XmlElement(name = "Options")
    protected HistoryFieldOptions options;
    @XmlElement(name = "AssignmentType", required = true)
    @XmlSchemaType(name = "string")
    protected AssignmentType assignmentType;
    @XmlAttribute(name = "Label")
    protected String label;
    @XmlAttribute(name = "Type", required = true)
    protected HistoryFormTypeEnum type;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link WFFormFieldValue }
     *     
     */
    public WFFormFieldValue getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link WFFormFieldValue }
     *     
     */
    public void setValue(WFFormFieldValue value) {
        this.value = value;
    }

    /**
     * Gets the value of the options property.
     * 
     * @return
     *     possible object is
     *     {@link HistoryFieldOptions }
     *     
     */
    public HistoryFieldOptions getOptions() {
        return options;
    }

    /**
     * Sets the value of the options property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoryFieldOptions }
     *     
     */
    public void setOptions(HistoryFieldOptions value) {
        this.options = value;
    }

    /**
     * Gets the value of the assignmentType property.
     * 
     * @return
     *     possible object is
     *     {@link AssignmentType }
     *     
     */
    public AssignmentType getAssignmentType() {
        return assignmentType;
    }

    /**
     * Sets the value of the assignmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssignmentType }
     *     
     */
    public void setAssignmentType(AssignmentType value) {
        this.assignmentType = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link HistoryFormTypeEnum }
     *     
     */
    public HistoryFormTypeEnum getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoryFormTypeEnum }
     *     
     */
    public void setType(HistoryFormTypeEnum value) {
        this.type = value;
    }

}
