//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform.workflow;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HistoryFieldOptions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HistoryFieldOptions"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="TextHistoryFieldOptions" type="{http://dev.docuware.com/schema/public/services/platform/workflow}TextHistoryFieldOptions"/&gt;
 *         &lt;element name="NumericHistoryFieldOptions" type="{http://dev.docuware.com/schema/public/services/platform/workflow}NumericHistoryFieldOptions"/&gt;
 *         &lt;element name="TableHistoryFieldOptions" type="{http://dev.docuware.com/schema/public/services/platform/workflow}TableHistoryFieldOptions"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HistoryFieldOptions", propOrder = {
    "textHistoryFieldOptions",
    "numericHistoryFieldOptions",
    "tableHistoryFieldOptions"
})
public class HistoryFieldOptions {

    @XmlElement(name = "TextHistoryFieldOptions")
    protected TextHistoryFieldOptions textHistoryFieldOptions;
    @XmlElement(name = "NumericHistoryFieldOptions")
    protected NumericHistoryFieldOptions numericHistoryFieldOptions;
    @XmlElement(name = "TableHistoryFieldOptions")
    protected TableHistoryFieldOptions tableHistoryFieldOptions;

    /**
     * Gets the value of the textHistoryFieldOptions property.
     * 
     * @return
     *     possible object is
     *     {@link TextHistoryFieldOptions }
     *     
     */
    public TextHistoryFieldOptions getTextHistoryFieldOptions() {
        return textHistoryFieldOptions;
    }

    /**
     * Sets the value of the textHistoryFieldOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextHistoryFieldOptions }
     *     
     */
    public void setTextHistoryFieldOptions(TextHistoryFieldOptions value) {
        this.textHistoryFieldOptions = value;
    }

    /**
     * Gets the value of the numericHistoryFieldOptions property.
     * 
     * @return
     *     possible object is
     *     {@link NumericHistoryFieldOptions }
     *     
     */
    public NumericHistoryFieldOptions getNumericHistoryFieldOptions() {
        return numericHistoryFieldOptions;
    }

    /**
     * Sets the value of the numericHistoryFieldOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumericHistoryFieldOptions }
     *     
     */
    public void setNumericHistoryFieldOptions(NumericHistoryFieldOptions value) {
        this.numericHistoryFieldOptions = value;
    }

    /**
     * Gets the value of the tableHistoryFieldOptions property.
     * 
     * @return
     *     possible object is
     *     {@link TableHistoryFieldOptions }
     *     
     */
    public TableHistoryFieldOptions getTableHistoryFieldOptions() {
        return tableHistoryFieldOptions;
    }

    /**
     * Sets the value of the tableHistoryFieldOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableHistoryFieldOptions }
     *     
     */
    public void setTableHistoryFieldOptions(TableHistoryFieldOptions value) {
        this.tableHistoryFieldOptions = value;
    }

}
