//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform.workflow;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.docuware.dev.schema._public.services.platform.workflow package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.docuware.dev.schema._public.services.platform.workflow
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Workflows }
     * 
     */
    public Workflows createWorkflows() {
        return new Workflows();
    }

    /**
     * Create an instance of {@link WorkflowTasksCount }
     * 
     */
    public WorkflowTasksCount createWorkflowTasksCount() {
        return new WorkflowTasksCount();
    }

    /**
     * Create an instance of {@link Workflow }
     * 
     */
    public Workflow createWorkflow() {
        return new Workflow();
    }

    /**
     * Create an instance of {@link WorkflowBehaviorOptions }
     * 
     */
    public WorkflowBehaviorOptions createWorkflowBehaviorOptions() {
        return new WorkflowBehaviorOptions();
    }

    /**
     * Create an instance of {@link ColumnValues }
     * 
     */
    public ColumnValues createColumnValues() {
        return new ColumnValues();
    }

    /**
     * Create an instance of {@link TaskFieldValue }
     * 
     */
    public TaskFieldValue createTaskFieldValue() {
        return new TaskFieldValue();
    }

    /**
     * Create an instance of {@link ColumnValue }
     * 
     */
    public ColumnValue createColumnValue() {
        return new ColumnValue();
    }

    /**
     * Create an instance of {@link WorkflowTasks }
     * 
     */
    public WorkflowTasks createWorkflowTasks() {
        return new WorkflowTasks();
    }

    /**
     * Create an instance of {@link TasksQuery }
     * 
     */
    public TasksQuery createTasksQuery() {
        return new TasksQuery();
    }

    /**
     * Create an instance of {@link WorkflowTask }
     * 
     */
    public WorkflowTask createWorkflowTask() {
        return new WorkflowTask();
    }

    /**
     * Create an instance of {@link ReadStatus }
     * 
     */
    public ReadStatus createReadStatus() {
        return new ReadStatus();
    }

    /**
     * Create an instance of {@link DecisionsStampSettings }
     * 
     */
    public DecisionsStampSettings createDecisionsStampSettings() {
        return new DecisionsStampSettings();
    }

    /**
     * Create an instance of {@link WorkflowStampsSettings }
     * 
     */
    public WorkflowStampsSettings createWorkflowStampsSettings() {
        return new WorkflowStampsSettings();
    }

    /**
     * Create an instance of {@link TaskOperations }
     * 
     */
    public TaskOperations createTaskOperations() {
        return new TaskOperations();
    }

    /**
     * Create an instance of {@link BaseTaskOperations }
     * 
     */
    public BaseTaskOperations createBaseTaskOperations() {
        return new BaseTaskOperations();
    }

    /**
     * Create an instance of {@link WorkflowDocumentHistory }
     * 
     */
    public WorkflowDocumentHistory createWorkflowDocumentHistory() {
        return new WorkflowDocumentHistory();
    }

    /**
     * Create an instance of {@link Instance }
     * 
     */
    public Instance createInstance() {
        return new Instance();
    }

    /**
     * Create an instance of {@link ExtendedUserOperations }
     * 
     */
    public ExtendedUserOperations createExtendedUserOperations() {
        return new ExtendedUserOperations();
    }

    /**
     * Create an instance of {@link ExtendedControllerOperations }
     * 
     */
    public ExtendedControllerOperations createExtendedControllerOperations() {
        return new ExtendedControllerOperations();
    }

    /**
     * Create an instance of {@link ReassignmentData }
     * 
     */
    public ReassignmentData createReassignmentData() {
        return new ReassignmentData();
    }

    /**
     * Create an instance of {@link AssignedItem }
     * 
     */
    public AssignedItem createAssignedItem() {
        return new AssignedItem();
    }

    /**
     * Create an instance of {@link ColumnsDefinition }
     * 
     */
    public ColumnsDefinition createColumnsDefinition() {
        return new ColumnsDefinition();
    }

    /**
     * Create an instance of {@link Column }
     * 
     */
    public Column createColumn() {
        return new Column();
    }

    /**
     * Create an instance of {@link ColumnSortOrder }
     * 
     */
    public ColumnSortOrder createColumnSortOrder() {
        return new ColumnSortOrder();
    }

    /**
     * Create an instance of {@link ColumnOptions }
     * 
     */
    public ColumnOptions createColumnOptions() {
        return new ColumnOptions();
    }

    /**
     * Create an instance of {@link TextColumn }
     * 
     */
    public TextColumn createTextColumn() {
        return new TextColumn();
    }

    /**
     * Create an instance of {@link NumberColumn }
     * 
     */
    public NumberColumn createNumberColumn() {
        return new NumberColumn();
    }

    /**
     * Create an instance of {@link DateColumn }
     * 
     */
    public DateColumn createDateColumn() {
        return new DateColumn();
    }

    /**
     * Create an instance of {@link Decisions }
     * 
     */
    public Decisions createDecisions() {
        return new Decisions();
    }

    /**
     * Create an instance of {@link DecisionStamps }
     * 
     */
    public DecisionStamps createDecisionStamps() {
        return new DecisionStamps();
    }

    /**
     * Create an instance of {@link Decision }
     * 
     */
    public Decision createDecision() {
        return new Decision();
    }

    /**
     * Create an instance of {@link DecisionOperations }
     * 
     */
    public DecisionOperations createDecisionOperations() {
        return new DecisionOperations();
    }

    /**
     * Create an instance of {@link BaseDecisionOperations }
     * 
     */
    public BaseDecisionOperations createBaseDecisionOperations() {
        return new BaseDecisionOperations();
    }

    /**
     * Create an instance of {@link ExtendedDecisionOperations }
     * 
     */
    public ExtendedDecisionOperations createExtendedDecisionOperations() {
        return new ExtendedDecisionOperations();
    }

    /**
     * Create an instance of {@link TaskFormField }
     * 
     */
    public TaskFormField createTaskFormField() {
        return new TaskFormField();
    }

    /**
     * Create an instance of {@link BaseForm }
     * 
     */
    public BaseForm createBaseForm() {
        return new BaseForm();
    }

    /**
     * Create an instance of {@link CommonFormField }
     * 
     */
    public CommonFormField createCommonFormField() {
        return new CommonFormField();
    }

    /**
     * Create an instance of {@link SelectListFilter }
     * 
     */
    public SelectListFilter createSelectListFilter() {
        return new SelectListFilter();
    }

    /**
     * Create an instance of {@link TableSelectListFilter }
     * 
     */
    public TableSelectListFilter createTableSelectListFilter() {
        return new TableSelectListFilter();
    }

    /**
     * Create an instance of {@link MultiValueField }
     * 
     */
    public MultiValueField createMultiValueField() {
        return new MultiValueField();
    }

    /**
     * Create an instance of {@link UserField }
     * 
     */
    public UserField createUserField() {
        return new UserField();
    }

    /**
     * Create an instance of {@link RoleField }
     * 
     */
    public RoleField createRoleField() {
        return new RoleField();
    }

    /**
     * Create an instance of {@link SubstitutionRuleField }
     * 
     */
    public SubstitutionRuleField createSubstitutionRuleField() {
        return new SubstitutionRuleField();
    }

    /**
     * Create an instance of {@link TaskTableField }
     * 
     */
    public TaskTableField createTaskTableField() {
        return new TaskTableField();
    }

    /**
     * Create an instance of {@link TaskTableFieldInitialValues }
     * 
     */
    public TaskTableFieldInitialValues createTaskTableFieldInitialValues() {
        return new TaskTableFieldInitialValues();
    }

    /**
     * Create an instance of {@link TaskTableColumn }
     * 
     */
    public TaskTableColumn createTaskTableColumn() {
        return new TaskTableColumn();
    }

    /**
     * Create an instance of {@link TaskTableColumnBase }
     * 
     */
    public TaskTableColumnBase createTaskTableColumnBase() {
        return new TaskTableColumnBase();
    }

    /**
     * Create an instance of {@link TaskTextField }
     * 
     */
    public TaskTextField createTaskTextField() {
        return new TaskTextField();
    }

    /**
     * Create an instance of {@link TaskDateTimeField }
     * 
     */
    public TaskDateTimeField createTaskDateTimeField() {
        return new TaskDateTimeField();
    }

    /**
     * Create an instance of {@link KeywordsField }
     * 
     */
    public KeywordsField createKeywordsField() {
        return new KeywordsField();
    }

    /**
     * Create an instance of {@link TaskNumberField }
     * 
     */
    public TaskNumberField createTaskNumberField() {
        return new TaskNumberField();
    }

    /**
     * Create an instance of {@link TaskTableNumberField }
     * 
     */
    public TaskTableNumberField createTaskTableNumberField() {
        return new TaskTableNumberField();
    }

    /**
     * Create an instance of {@link LinkForm }
     * 
     */
    public LinkForm createLinkForm() {
        return new LinkForm();
    }

    /**
     * Create an instance of {@link LinkParameter }
     * 
     */
    public LinkParameter createLinkParameter() {
        return new LinkParameter();
    }

    /**
     * Create an instance of {@link DescriptionFormField }
     * 
     */
    public DescriptionFormField createDescriptionFormField() {
        return new DescriptionFormField();
    }

    /**
     * Create an instance of {@link FieldMask }
     * 
     */
    public FieldMask createFieldMask() {
        return new FieldMask();
    }

    /**
     * Create an instance of {@link ConfirmedData }
     * 
     */
    public ConfirmedData createConfirmedData() {
        return new ConfirmedData();
    }

    /**
     * Create an instance of {@link StampPositionData }
     * 
     */
    public StampPositionData createStampPositionData() {
        return new StampPositionData();
    }

    /**
     * Create an instance of {@link StampConfirmedData }
     * 
     */
    public StampConfirmedData createStampConfirmedData() {
        return new StampConfirmedData();
    }

    /**
     * Create an instance of {@link ConfirmedField }
     * 
     */
    public ConfirmedField createConfirmedField() {
        return new ConfirmedField();
    }

    /**
     * Create an instance of {@link HistorySteps }
     * 
     */
    public HistorySteps createHistorySteps() {
        return new HistorySteps();
    }

    /**
     * Create an instance of {@link HistoryStep }
     * 
     */
    public HistoryStep createHistoryStep() {
        return new HistoryStep();
    }

    /**
     * Create an instance of {@link HistoryStepInfo }
     * 
     */
    public HistoryStepInfo createHistoryStepInfo() {
        return new HistoryStepInfo();
    }

    /**
     * Create an instance of {@link ErrorHistoryStep }
     * 
     */
    public ErrorHistoryStep createErrorHistoryStep() {
        return new ErrorHistoryStep();
    }

    /**
     * Create an instance of {@link TimeoutHistoryStep }
     * 
     */
    public TimeoutHistoryStep createTimeoutHistoryStep() {
        return new TimeoutHistoryStep();
    }

    /**
     * Create an instance of {@link StopHistoryStep }
     * 
     */
    public StopHistoryStep createStopHistoryStep() {
        return new StopHistoryStep();
    }

    /**
     * Create an instance of {@link EndHistoryStep }
     * 
     */
    public EndHistoryStep createEndHistoryStep() {
        return new EndHistoryStep();
    }

    /**
     * Create an instance of {@link StartHistoryStep }
     * 
     */
    public StartHistoryStep createStartHistoryStep() {
        return new StartHistoryStep();
    }

    /**
     * Create an instance of {@link DecisionHistoryStep }
     * 
     */
    public DecisionHistoryStep createDecisionHistoryStep() {
        return new DecisionHistoryStep();
    }

    /**
     * Create an instance of {@link GeneralErrorDecisionHistoryStep }
     * 
     */
    public GeneralErrorDecisionHistoryStep createGeneralErrorDecisionHistoryStep() {
        return new GeneralErrorDecisionHistoryStep();
    }

    /**
     * Create an instance of {@link FormFieldListValue }
     * 
     */
    public FormFieldListValue createFormFieldListValue() {
        return new FormFieldListValue();
    }

    /**
     * Create an instance of {@link WFFormFieldValue }
     * 
     */
    public WFFormFieldValue createWFFormFieldValue() {
        return new WFFormFieldValue();
    }

    /**
     * Create an instance of {@link HistoryField }
     * 
     */
    public HistoryField createHistoryField() {
        return new HistoryField();
    }

    /**
     * Create an instance of {@link FileCabinetHistoryField }
     * 
     */
    public FileCabinetHistoryField createFileCabinetHistoryField() {
        return new FileCabinetHistoryField();
    }

    /**
     * Create an instance of {@link HistoryFieldOptions }
     * 
     */
    public HistoryFieldOptions createHistoryFieldOptions() {
        return new HistoryFieldOptions();
    }

    /**
     * Create an instance of {@link TableHistoryFieldOptions }
     * 
     */
    public TableHistoryFieldOptions createTableHistoryFieldOptions() {
        return new TableHistoryFieldOptions();
    }

    /**
     * Create an instance of {@link TextTableColumnOptions }
     * 
     */
    public TextTableColumnOptions createTextTableColumnOptions() {
        return new TextTableColumnOptions();
    }

    /**
     * Create an instance of {@link NumberTableColumnOptions }
     * 
     */
    public NumberTableColumnOptions createNumberTableColumnOptions() {
        return new NumberTableColumnOptions();
    }

    /**
     * Create an instance of {@link DateTableColumnOptions }
     * 
     */
    public DateTableColumnOptions createDateTableColumnOptions() {
        return new DateTableColumnOptions();
    }

    /**
     * Create an instance of {@link TableColumnOptions }
     * 
     */
    public TableColumnOptions createTableColumnOptions() {
        return new TableColumnOptions();
    }

    /**
     * Create an instance of {@link TableColumnsDefinition }
     * 
     */
    public TableColumnsDefinition createTableColumnsDefinition() {
        return new TableColumnsDefinition();
    }

    /**
     * Create an instance of {@link TextHistoryFieldOptions }
     * 
     */
    public TextHistoryFieldOptions createTextHistoryFieldOptions() {
        return new TextHistoryFieldOptions();
    }

    /**
     * Create an instance of {@link NumericHistoryFieldOptions }
     * 
     */
    public NumericHistoryFieldOptions createNumericHistoryFieldOptions() {
        return new NumericHistoryFieldOptions();
    }

    /**
     * Create an instance of {@link ReassignHistoryStep }
     * 
     */
    public ReassignHistoryStep createReassignHistoryStep() {
        return new ReassignHistoryStep();
    }

    /**
     * Create an instance of {@link AssignDataHistoryStep }
     * 
     */
    public AssignDataHistoryStep createAssignDataHistoryStep() {
        return new AssignDataHistoryStep();
    }

    /**
     * Create an instance of {@link EmailHistoryStep }
     * 
     */
    public EmailHistoryStep createEmailHistoryStep() {
        return new EmailHistoryStep();
    }

    /**
     * Create an instance of {@link AssignToHistoryStep }
     * 
     */
    public AssignToHistoryStep createAssignToHistoryStep() {
        return new AssignToHistoryStep();
    }

    /**
     * Create an instance of {@link OutOfOfficeHistoryStep }
     * 
     */
    public OutOfOfficeHistoryStep createOutOfOfficeHistoryStep() {
        return new OutOfOfficeHistoryStep();
    }

    /**
     * Create an instance of {@link RequestDecisionHistoryStep }
     * 
     */
    public RequestDecisionHistoryStep createRequestDecisionHistoryStep() {
        return new RequestDecisionHistoryStep();
    }

    /**
     * Create an instance of {@link RequestStartHistoryStep }
     * 
     */
    public RequestStartHistoryStep createRequestStartHistoryStep() {
        return new RequestStartHistoryStep();
    }

    /**
     * Create an instance of {@link RequestEndHistoryStep }
     * 
     */
    public RequestEndHistoryStep createRequestEndHistoryStep() {
        return new RequestEndHistoryStep();
    }

    /**
     * Create an instance of {@link WaitHistoryStep }
     * 
     */
    public WaitHistoryStep createWaitHistoryStep() {
        return new WaitHistoryStep();
    }

    /**
     * Create an instance of {@link EventHistoryStep }
     * 
     */
    public EventHistoryStep createEventHistoryStep() {
        return new EventHistoryStep();
    }

    /**
     * Create an instance of {@link ConditionHistoryStep }
     * 
     */
    public ConditionHistoryStep createConditionHistoryStep() {
        return new ConditionHistoryStep();
    }

    /**
     * Create an instance of {@link WebServiceHistoryStep }
     * 
     */
    public WebServiceHistoryStep createWebServiceHistoryStep() {
        return new WebServiceHistoryStep();
    }

    /**
     * Create an instance of {@link InstanceHistory }
     * 
     */
    public InstanceHistory createInstanceHistory() {
        return new InstanceHistory();
    }

    /**
     * Create an instance of {@link WorkflowRequests }
     * 
     */
    public WorkflowRequests createWorkflowRequests() {
        return new WorkflowRequests();
    }

    /**
     * Create an instance of {@link RequestTasks }
     * 
     */
    public RequestTasks createRequestTasks() {
        return new RequestTasks();
    }

    /**
     * Create an instance of {@link RequestTask }
     * 
     */
    public RequestTask createRequestTask() {
        return new RequestTask();
    }

    /**
     * Create an instance of {@link RequestDecision }
     * 
     */
    public RequestDecision createRequestDecision() {
        return new RequestDecision();
    }

    /**
     * Create an instance of {@link RequestConfirmedData }
     * 
     */
    public RequestConfirmedData createRequestConfirmedData() {
        return new RequestConfirmedData();
    }

    /**
     * Create an instance of {@link OwnWorkflows }
     * 
     */
    public OwnWorkflows createOwnWorkflows() {
        return new OwnWorkflows();
    }

    /**
     * Create an instance of {@link OwnWorkflow }
     * 
     */
    public OwnWorkflow createOwnWorkflow() {
        return new OwnWorkflow();
    }

    /**
     * Create an instance of {@link RequestSettings }
     * 
     */
    public RequestSettings createRequestSettings() {
        return new RequestSettings();
    }

    /**
     * Create an instance of {@link RequestDataDecision }
     * 
     */
    public RequestDataDecision createRequestDataDecision() {
        return new RequestDataDecision();
    }

    /**
     * Create an instance of {@link RequestDecisionSettings }
     * 
     */
    public RequestDecisionSettings createRequestDecisionSettings() {
        return new RequestDecisionSettings();
    }

}
