//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform.workflow;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 *  Data to trigger new request. 
 * 
 * <p>Java class for RequestSettings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestSettings"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Decisions" type="{http://dev.docuware.com/schema/public/services/platform/workflow}RequestDecisionSettings" maxOccurs="unbounded"/&gt;
 *         &lt;element name="AssignedItem" type="{http://dev.docuware.com/schema/public/services/platform/workflow}AssignedItem" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Description" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="IsSequence" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="IsAny" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="DocId" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="FcGuid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DocumentName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="StampDocument" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestSettings", propOrder = {
    "decisions",
    "assignedItem"
})
public class RequestSettings {

    @XmlElement(name = "Decisions", required = true)
    protected List<RequestDecisionSettings> decisions;
    @XmlElement(name = "AssignedItem")
    protected List<AssignedItem> assignedItem;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "Description", required = true)
    protected String description;
    @XmlAttribute(name = "IsSequence")
    protected Boolean isSequence;
    @XmlAttribute(name = "IsAny", required = true)
    protected boolean isAny;
    @XmlAttribute(name = "DocId", required = true)
    protected int docId;
    @XmlAttribute(name = "FcGuid", required = true)
    protected String fcGuid;
    @XmlAttribute(name = "DocumentName")
    protected String documentName;
    @XmlAttribute(name = "StampDocument", required = true)
    protected boolean stampDocument;

    /**
     * Gets the value of the decisions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the decisions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDecisions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RequestDecisionSettings }
     * 
     * 
     */
    public List<RequestDecisionSettings> getDecisions() {
        if (decisions == null) {
            decisions = new ArrayList<RequestDecisionSettings>();
        }
        return this.decisions;
    }

    /**
     * Gets the value of the assignedItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assignedItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssignedItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssignedItem }
     * 
     * 
     */
    public List<AssignedItem> getAssignedItem() {
        if (assignedItem == null) {
            assignedItem = new ArrayList<AssignedItem>();
        }
        return this.assignedItem;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the isSequence property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsSequence() {
        if (isSequence == null) {
            return true;
        } else {
            return isSequence;
        }
    }

    /**
     * Sets the value of the isSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSequence(Boolean value) {
        this.isSequence = value;
    }

    /**
     * Gets the value of the isAny property.
     * 
     */
    public boolean isIsAny() {
        return isAny;
    }

    /**
     * Sets the value of the isAny property.
     * 
     */
    public void setIsAny(boolean value) {
        this.isAny = value;
    }

    /**
     * Gets the value of the docId property.
     * 
     */
    public int getDocId() {
        return docId;
    }

    /**
     * Sets the value of the docId property.
     * 
     */
    public void setDocId(int value) {
        this.docId = value;
    }

    /**
     * Gets the value of the fcGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFcGuid() {
        return fcGuid;
    }

    /**
     * Sets the value of the fcGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFcGuid(String value) {
        this.fcGuid = value;
    }

    /**
     * Gets the value of the documentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentName() {
        return documentName;
    }

    /**
     * Sets the value of the documentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentName(String value) {
        this.documentName = value;
    }

    /**
     * Gets the value of the stampDocument property.
     * 
     */
    public boolean isStampDocument() {
        return stampDocument;
    }

    /**
     * Sets the value of the stampDocument property.
     * 
     */
    public void setStampDocument(boolean value) {
        this.stampDocument = value;
    }

}
