//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.17 at 05:04:55 PM GMT+07:00 
//


package com.docuware.dev.schema._public.services.platform.workflow;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * A table number field.
 * 
 * <p>Java class for TaskTableNumberField complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaskTableNumberField"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://dev.docuware.com/schema/public/services/platform/workflow}TaskNumberField"&gt;
 *       &lt;attribute name="PrefillWithBalance" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="BalanceField" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaskTableNumberField")
public class TaskTableNumberField
    extends TaskNumberField
{

    @XmlAttribute(name = "PrefillWithBalance", required = true)
    protected boolean prefillWithBalance;
    @XmlAttribute(name = "BalanceField")
    protected String balanceField;

    /**
     * Gets the value of the prefillWithBalance property.
     * 
     */
    public boolean isPrefillWithBalance() {
        return prefillWithBalance;
    }

    /**
     * Sets the value of the prefillWithBalance property.
     * 
     */
    public void setPrefillWithBalance(boolean value) {
        this.prefillWithBalance = value;
    }

    /**
     * Gets the value of the balanceField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBalanceField() {
        return balanceField;
    }

    /**
     * Sets the value of the balanceField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBalanceField(String value) {
        this.balanceField = value;
    }

}
