RestClients:
  DocuWare:
    UUID: 02d1eec1-32e9-4316-afc3-793448486203
    Url: https://{host}/docuware/platform
    Icon: res:/webContent/icons/docuware.png
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    - com.axonivy.connector.docuware.connector.DocuWareAuthFeature
    - org.glassfish.jersey.media.multipart.MultiPartFeature
    Properties:
      PATH.host: ${ivy.var.docuwareConnector.host}
      UserName: ${ivy.var.docuwareConnector.username}
      Password: ${ivy.var.docuwareConnector.password}
      HostId: ${ivy.var.docuwareConnector.hostid}
      LogonUrl: ${ivy.var.docuwareConnector.logonurl}
      Organization: ${ivy.var.docuwareConnector.organization}
      com.sun.jersey.impl.client.httpclient.handleCookies: 'true'
      http.protocol.handle-redirects: 'true'
      JSON.Serialization.PROPERTY_INCLUSION: NON_NULL
      jersey.config.client.connectTimeout: ${ivy.var.docuwareConnector.connectTimeout}
    OpenAPI:
      SpecUrl: file:///X:/AxonIvy/marketplace/docuware/openapi-handmade.json
      Namespace: com.axonivy.connector.docuware.connector.model
