# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/rest-clients-1.json
RestClients:
  DocuWare:
    Name: DocuWare
    Url: URI.PLACEHOLDER
    Icon: res:/webContent/icons/docuware.png
    Features:
      - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
      - org.glassfish.jersey.media.multipart.MultiPartFeature
      - com.axonivy.connector.docuware.connector.auth.DocuWareAuthFeature
    Properties:
      com.sun.jersey.impl.client.httpclient.handleCookies: 'true'
      http.protocol.handle-redirects: 'true'
      JSON.Serialization.PROPERTY_INCLUSION: NON_NULL
    OpenAPI:
      SpecUrl: file:///X:/AxonIvy/marketplace/docuware/openapi-handmade.json
      Namespace: com.axonivy.connector.docuware.connector.model
    LegacyUUID: 02d1eec1-32e9-4316-afc3-793448486203
