RestClients:
  DocuWare:
    UUID: 02d1eec1-32e9-4316-afc3-793448486203
    Url: https://rch.docuware.cloud/docuware/platform
    Icon: res:/webContent/icons/docuware.png
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    - com.axonivy.connector.docuware.connector.DocuWareAuthFeature
    - org.glassfish.jersey.media.multipart.MultiPartFeature
    Properties:
      com.sun.jersey.impl.client.httpclient.handleCookies: 'true'
      http.protocol.handle-redirects: 'true'
      username: ${ivy.var.docuware_username}
      password: ${ivy.var.docuware_password}
      hostid: ${ivy.var.docuware_hostid}
      logonurl:
      JSON.Serialization.PROPERTY_INCLUSION: NON_NULL
    OpenAPI:
      SpecUrl: file:///X:/AxonIvy/marketplace/docuware/openapi-handmade.json
      Namespace: com.axonivy.connector.docuware.connector.model
