name: Release Drafter

permissions:
  contents: read

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  release_drafter:
    uses: axonivy-market/github-workflows/.github/workflows/release-drafter.yml@v5
